# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True)),
                ('counter', models.IntegerField(default=1, null=True)),
                ('poked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedpokes', to='loginapp.User')),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokerpokes', to='loginapp.User')),
            ],
        ),
    ]
